from config import load_prompt_template

MEETING_NOTES_PLACEHOLDER = "{{MEETING_NOTES}}"
TUNING_PLACEHOLDER = "{{TUNING_INSTRUCTIONS}}"
COPILOT_MODE_PLACEHOLDER = "{{COPILOT_MODE_INSTRUCTIONS}}"

SAMPLE_INSTRUCTION = (
    "(No meeting notes provided — generate a realistic sample output "
    "with 2–3 Epics and their Stories.)"
)

AGGRESSIVENESS_MAP = {
    1: (
        "Only create epics for explicitly agreed initiatives with clear ownership and "
        "multi-story scope. A single task, vague idea, or minor follow-up is NOT an epic — skip it."
    ),
    2: (
        "Create epics for committed work items that need structured tracking. "
        "Each epic must justify at least 2 stories. Skip discussion points, "
        "parking-lot items, and tasks someone can do in a day."
    ),
    3: (
        "Create epics for every work stream mentioned, including tentative or exploratory ones. "
        "Still require that each epic has enough substance for multiple stories — "
        "don't create single-story epics."
    ),
}

DETAIL_LEVEL_MAP = {
    "Brief": "For each Story, provide only: title and a one-sentence description. Leave all other fields empty.",
    "Standard": "For each Story, provide all fields: title, description, acceptance_criteria, due_date, priority, assignee, comment.",
    "Detailed": "For each Story, provide all fields with thorough descriptions. Write acceptance criteria as a numbered checklist. Include specific examples where relevant.",
}

COPILOT_MODE_MAP = {
    "in_meeting": (
        "COPILOT INSTRUCTIONS:\n"
        "You have access to this meeting's live transcript. Analyze it directly — do NOT ask for meeting notes.\n"
        "Focus on: decisions made, action items assigned, and deliverables committed to.\n"
        "Provide your complete response as a single downloadable .yaml file attachment.\n"
        "Do NOT format it as inline text, code blocks, or chat messages."
    ),
    "post_recap": (
        "COPILOT INSTRUCTIONS:\n"
        "The text in the MEETING NOTES section below is a meeting recap generated by Microsoft Teams Copilot.\n"
        "Convert it into the YAML structure specified above.\n"
        "Provide your complete response as a single downloadable .yaml file attachment.\n"
        "Do NOT format it as inline text, code blocks, or chat messages."
    ),
}

SUBTASKS_FORMAT = """\
      subtasks:
        - "Sub-task title 1"
        - "Sub-task title 2" """


def build_tuning_instructions(tuning: dict) -> str:
    aggressiveness = int(tuning.get("aggressiveness", 2))
    stories_min = int(tuning.get("stories_min", 2))
    stories_max = int(tuning.get("stories_max", 6))
    detail_level = tuning.get("detail_level", "Standard")
    include_subtasks = tuning.get("include_subtasks", False)

    lines = [
        "RULES:",
        f"- {AGGRESSIVENESS_MAP.get(aggressiveness, AGGRESSIVENESS_MAP[2])}",
        f"- Each Epic must have between {stories_min} and {stories_max} Stories.",
        f"- {DETAIL_LEVEL_MAP.get(detail_level, DETAIL_LEVEL_MAP['Standard'])}",
        "- Output ONLY valid YAML — no markdown fences, no explanations, no extra text.",
        "- Use ISO 8601 format for dates (YYYY-MM-DD) or leave empty string if unknown.",
        "- Priority must be one of: Low, Medium, High, Critical.",
        "- Assignee is a free-text name (leave empty if unknown).",
        "- acceptance_criteria is REQUIRED for every Epic and every Story. Write it as 1–5 concrete, testable statements (e.g. Given/When/Then or a numbered checklist). Never leave it as '...' or empty.",
    ]

    if include_subtasks:
        lines.append('- Each Story must also have a \'subtasks\' list with 2-4 brief sub-task titles.')

    return "\n".join(lines)


def build_prompt(meeting_notes: str, tuning: dict = None, copilot_mode: str = None) -> str:
    if tuning is None:
        tuning = {}

    template = load_prompt_template()
    tuning_block = build_tuning_instructions(tuning)

    if TUNING_PLACEHOLDER in template:
        template = template.replace(TUNING_PLACEHOLDER, tuning_block)
    else:
        # Legacy template without tuning placeholder — prepend tuning block
        template = tuning_block + "\n\n" + template

    # Inject copilot mode instructions
    mode_block = COPILOT_MODE_MAP.get(copilot_mode, "")
    if COPILOT_MODE_PLACEHOLDER in template:
        template = template.replace(COPILOT_MODE_PLACEHOLDER, mode_block)

    # In-meeting mode: Copilot reads the transcript directly — skip the meeting notes section
    if copilot_mode == "in_meeting":
        if "MEETING NOTES:\n" + MEETING_NOTES_PLACEHOLDER in template:
            # Remove the full section header + placeholder
            template = template.replace("MEETING NOTES:\n" + MEETING_NOTES_PLACEHOLDER, "")
        else:
            # Template has placeholder but no "MEETING NOTES:" header — just remove the placeholder
            template = template.replace(MEETING_NOTES_PLACEHOLDER, "")
        return template.rstrip()

    # All other modes: inject meeting notes (or sample)
    notes_content = meeting_notes.strip() if meeting_notes else ""
    if not notes_content:
        notes_content = SAMPLE_INSTRUCTION

    if MEETING_NOTES_PLACEHOLDER in template:
        return template.replace(MEETING_NOTES_PLACEHOLDER, notes_content)
    return template + "\n\n" + notes_content
